export const AuthTypes = {
  ADD_QUESTION: "ADD_QUESTION",
  UPDATE_QUESTION: "UPDATE_QUESTION",
  DELETE_QUESTION: "DELETE_QUESTION",
  ADD_IMAGE_TO_QUESTION: "ADD_IMAGE_TO_QUESTION",

  ADD_OPTION: "ADD_OPTION",
  UPDATE_OPTION: "UPDATE_OPTION",
  DELETE_OPTION: "DELETE_OPTION",
};
